Can't cache outside user directory so let's try this...

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -13,11 +13,9 @@ fi
 
 if [ "$(which ant)" == "" ]; then brew install ant; fi
 if [ "$(which android)" == "" ]; then
-  brew cask install android-sdk
+  echo "ERROR: Install Android SDK first.  Maybe use 'brew cask install android-sdk'.  Leaving this to you in case you want to handle this differently."
+  exit 1
 fi
-
-ANDROID_HOME=/usr/local/share/android-sdk
-export ANDROID_HOME
 
 sdkmanager "build-tools;23.0.2"
 sdkmanager "platforms;android-23"
