Download the Teak iOS/Android SDKs from S3 instead of re-building them.

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -2,27 +2,24 @@
 set -euo pipefail
 IFS=$'\n\t'
 
-(
-  cd ..
-  if [ ! -e teak-android ]; then
-    git clone git@github.com:GoCarrot/teak-android.git
-  fi
-  (
-    cd teak-android
-    git pull
-    ./setup
-  )
+brew update
+brew tap caskroom/cask
 
-  if [ ! -e teak-ios ]; then
-    git clone git@github.com:GoCarrot/teak-ios.git
-  fi
-  (
-    cd teak-ios
-    git pull
-    ./setup
-  )
-)
+# TODO: Ensure both Brew and Caskroom are set up.
+if [ "$(which java)" == "" ]; then
+  echo "ERROR: Install JDK first.  Maybe use 'brew cask install java'.  Leaving this to you in case you want to handle this differently."
+  exit 1
+fi
 
+if [ "$(which ant)" == "" ]; then brew install ant; fi
+if [ "$(which android)" == "" ]; then
+  brew cask install android-sdk
+fi
+
+echo y | android update sdk --all --no-ui --filter 'tools,platform-tools'
+echo y | android update sdk --all --no-ui --filter 'android-23'
+echo y | android update sdk --all --no-ui --filter 'build-tools-23.0.2'
+echo y | android update sdk --all --no-ui --filter 'extra-google-m2repository'
 echo y | android update sdk --all --no-ui --filter 'extra-android-m2repository'
 
 if [ "$(which aws)" == "" ]; then brew install awscli; fi
